<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.6.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SaveTheStock.Application\SaveTheStock.Application.csproj" />
    <ProjectReference Include="..\SaveTheStock.Infrastructure\SaveTheStock.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Controllers/**/*.cs" />
    <Compile Include="Contracts/**/*.cs" />
    <Compile Include="Options/**/*.cs" />
    <Compile Include="Security/**/*.cs" />
    <Compile Include="Services/**/*.cs" />
    <Compile Include="Program.cs" />
    <Compile Include="Program.Partial.cs" />
  </ItemGroup>

</Project>
