services:
  postgres:
    image: postgres:16
    container_name: savethestock-db
    restart: always
    environment:
      POSTGRES_DB: savethestock
      POSTGRES_USER: savethestock
      POSTGRES_PASSWORD: savethestock
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
