// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaveTheStock.Infrastructure.Persistence;

#nullable disable

namespace SaveTheStock.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301162548_AddLotReceptionTenantFk")]
    partial class AddLotReceptionTenantFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_account_company_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_account_email");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasAlternateKey("CompanyId", "Id")
                        .HasName("ak_categories_company_id_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_categories_company_id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_company_id_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_company");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("HasIssue")
                        .HasColumnType("boolean")
                        .HasColumnName("has_issue");

                    b.Property<string>("IssueNote")
                        .HasColumnType("text")
                        .HasColumnName("issue_note");

                    b.Property<string>("LotCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_code");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("QuantityInitial")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_initial");

                    b.Property<decimal>("QuantityRemaining")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity_remaining");

                    b.Property<Guid?>("ReceptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("reception_id");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_cost");

                    b.HasKey("Id")
                        .HasName("pk_lots");

                    b.HasAlternateKey("CompanyId", "Id")
                        .HasName("ak_lots_company_id_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_lots_company_id");

                    b.HasIndex("CompanyId", "ProductId")
                        .HasDatabaseName("ix_lots_company_id_product_id");

                    b.HasIndex("CompanyId", "ReceptionId")
                        .HasDatabaseName("ix_lots_company_id_reception_id");

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AlertThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("alert_threshold");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasAlternateKey("CompanyId", "Id")
                        .HasName("ak_products_company_id_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_products_company_id");

                    b.HasIndex("CompanyId", "CategoryId")
                        .HasDatabaseName("ix_products_company_id_category_id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_products_company_id_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Reception", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("HasIssue")
                        .HasColumnType("boolean")
                        .HasColumnName("has_issue");

                    b.Property<string>("IssueNote")
                        .HasColumnType("text")
                        .HasColumnName("issue_note");

                    b.Property<DateOnly>("ReceptionDate")
                        .HasColumnType("date")
                        .HasColumnName("reception_date");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id")
                        .HasName("pk_receptions");

                    b.HasAlternateKey("CompanyId", "Id")
                        .HasName("ak_receptions_company_id_id");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_receptions_account_id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_receptions_company_id");

                    b.HasIndex("CompanyId", "ReceptionDate")
                        .HasDatabaseName("ix_receptions_company_id_reception_date");

                    b.ToTable("receptions", (string)null);
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Account", b =>
                {
                    b.HasOne("SaveTheStock.Domain.Entities.Company", "Company")
                        .WithMany("Accounts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Lot", b =>
                {
                    b.HasOne("SaveTheStock.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("CompanyId", "ProductId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lots_products_company_id_product_id");

                    b.HasOne("SaveTheStock.Domain.Entities.Reception", null)
                        .WithMany()
                        .HasForeignKey("CompanyId", "ReceptionId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lots_receptions_company_id_reception_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Product", b =>
                {
                    b.HasOne("SaveTheStock.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId", "CategoryId")
                        .HasPrincipalKey("CompanyId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_company_id_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Reception", b =>
                {
                    b.HasOne("SaveTheStock.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_receptions_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SaveTheStock.Domain.Entities.Company", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
